# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from v2.models.base_model_ import Model
from v2.models.link_type import LinkType  # noqa: F401,E501
from v2 import util


class CaReconfNotificationLinks(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, subscription: LinkType=None):  # noqa: E501
        """CaReconfNotificationLinks - a model defined in Swagger

        :param subscription: The subscription of this CaReconfNotificationLinks.  # noqa: E501
        :type subscription: LinkType
        """
        self.swagger_types = {
            'subscription': LinkType
        }

        self.attribute_map = {
            'subscription': 'subscription'
        }
        self._subscription = subscription

    @classmethod
    def from_dict(cls, dikt) -> 'CaReconfNotificationLinks':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CaReconfNotification__links of this CaReconfNotificationLinks.  # noqa: E501
        :rtype: CaReconfNotificationLinks
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subscription(self) -> LinkType:
        """Gets the subscription of this CaReconfNotificationLinks.


        :return: The subscription of this CaReconfNotificationLinks.
        :rtype: LinkType
        """
        return self._subscription

    @subscription.setter
    def subscription(self, subscription: LinkType):
        """Sets the subscription of this CaReconfNotificationLinks.


        :param subscription: The subscription of this CaReconfNotificationLinks.
        :type subscription: LinkType
        """
        if subscription is None:
            raise ValueError("Invalid value for `subscription`, must not be `None`")  # noqa: E501

        self._subscription = subscription
