# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_notification import InlineNotification  # noqa: F401,E501
from swagger_server.models.links2 import Links2  # noqa: F401,E501
from swagger_server.models.time_stamp import TimeStamp  # noqa: F401,E501
from swagger_server import util


class ExpiryNotification(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, notification_type: str=None, links: Links2=None, expiry_deadline: TimeStamp=None, time_stamp: TimeStamp=None):  # noqa: E501
        """ExpiryNotification - a model defined in Swagger

        :param notification_type: The notification_type of this ExpiryNotification.  # noqa: E501
        :type notification_type: str
        :param links: The links of this ExpiryNotification.  # noqa: E501
        :type links: Links2
        :param expiry_deadline: The expiry_deadline of this ExpiryNotification.  # noqa: E501
        :type expiry_deadline: TimeStamp
        :param time_stamp: The time_stamp of this ExpiryNotification.  # noqa: E501
        :type time_stamp: TimeStamp
        """
        self.swagger_types = {
            'notification_type': str,
            'links': Links2,
            'expiry_deadline': TimeStamp,
            'time_stamp': TimeStamp
        }

        self.attribute_map = {
            'notification_type': 'notificationType',
            'links': '_links',
            'expiry_deadline': 'expiryDeadline',
            'time_stamp': 'timeStamp'
        }
        self._notification_type = notification_type
        self._links = links
        self._expiry_deadline = expiry_deadline
        self._time_stamp = time_stamp

    @classmethod
    def from_dict(cls, dikt) -> 'ExpiryNotification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExpiryNotification of this ExpiryNotification.  # noqa: E501
        :rtype: ExpiryNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_type(self) -> str:
        """Gets the notification_type of this ExpiryNotification.


        :return: The notification_type of this ExpiryNotification.
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type: str):
        """Sets the notification_type of this ExpiryNotification.


        :param notification_type: The notification_type of this ExpiryNotification.
        :type notification_type: str
        """
        if notification_type is None:
            raise ValueError("Invalid value for `notification_type`, must not be `None`")  # noqa: E501

        self._notification_type = notification_type

    @property
    def links(self) -> Links2:
        """Gets the links of this ExpiryNotification.


        :return: The links of this ExpiryNotification.
        :rtype: Links2
        """
        return self._links

    @links.setter
    def links(self, links: Links2):
        """Sets the links of this ExpiryNotification.


        :param links: The links of this ExpiryNotification.
        :type links: Links2
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def expiry_deadline(self) -> TimeStamp:
        """Gets the expiry_deadline of this ExpiryNotification.


        :return: The expiry_deadline of this ExpiryNotification.
        :rtype: TimeStamp
        """
        return self._expiry_deadline

    @expiry_deadline.setter
    def expiry_deadline(self, expiry_deadline: TimeStamp):
        """Sets the expiry_deadline of this ExpiryNotification.


        :param expiry_deadline: The expiry_deadline of this ExpiryNotification.
        :type expiry_deadline: TimeStamp
        """
        if expiry_deadline is None:
            raise ValueError("Invalid value for `expiry_deadline`, must not be `None`")  # noqa: E501

        self._expiry_deadline = expiry_deadline

    @property
    def time_stamp(self) -> TimeStamp:
        """Gets the time_stamp of this ExpiryNotification.


        :return: The time_stamp of this ExpiryNotification.
        :rtype: TimeStamp
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp: TimeStamp):
        """Sets the time_stamp of this ExpiryNotification.


        :param time_stamp: The time_stamp of this ExpiryNotification.
        :type time_stamp: TimeStamp
        """

        self._time_stamp = time_stamp
