# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from v2.models.base_model_ import Model
from v2.models_notification.ca_reconf_notification_links import CaReconfNotificationLinks  # noqa: F401,E501
from v2.models_notification.inline_notification import InlineNotification  # noqa: F401,E501
from v2 import util


class TestNotification(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, notification_type: str=None, links: CaReconfNotificationLinks=None):  # noqa: E501
        """TestNotification - a model defined in Swagger

        :param notification_type: The notification_type of this TestNotification.  # noqa: E501
        :type notification_type: str
        :param links: The links of this TestNotification.  # noqa: E501
        :type links: CaReconfNotificationLinks
        """
        self.swagger_types = {
            'notification_type': str,
            'links': CaReconfNotificationLinks
        }

        self.attribute_map = {
            'notification_type': 'notificationType',
            'links': '_links'
        }
        self._notification_type = notification_type
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'TestNotification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TestNotification of this TestNotification.  # noqa: E501
        :rtype: TestNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_type(self) -> str:
        """Gets the notification_type of this TestNotification.


        :return: The notification_type of this TestNotification.
        :rtype: str
        """
        return self._notification_type

    @notification_type.setter
    def notification_type(self, notification_type: str):
        """Sets the notification_type of this TestNotification.


        :param notification_type: The notification_type of this TestNotification.
        :type notification_type: str
        """
        if notification_type is None:
            raise ValueError("Invalid value for `notification_type`, must not be `None`")  # noqa: E501

        self._notification_type = notification_type

    @property
    def links(self) -> CaReconfNotificationLinks:
        """Gets the links of this TestNotification.


        :return: The links of this TestNotification.
        :rtype: CaReconfNotificationLinks
        """
        return self._links

    @links.setter
    def links(self, links: CaReconfNotificationLinks):
        """Sets the links of this TestNotification.


        :param links: The links of this TestNotification.
        :type links: CaReconfNotificationLinks
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links
