# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.qos_information2 import QosInformation2  # noqa: F401,E501
from swagger_server import util


class ErabQosParameters2(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, qci: int=None, qos_information: QosInformation2=None):  # noqa: E501
        """ErabQosParameters2 - a model defined in Swagger

        :param qci: The qci of this ErabQosParameters2.  # noqa: E501
        :type qci: int
        :param qos_information: The qos_information of this ErabQosParameters2.  # noqa: E501
        :type qos_information: QosInformation2
        """
        self.swagger_types = {
            'qci': int,
            'qos_information': QosInformation2
        }

        self.attribute_map = {
            'qci': 'qci',
            'qos_information': 'qosInformation'
        }
        self._qci = qci
        self._qos_information = qos_information

    @classmethod
    def from_dict(cls, dikt) -> 'ErabQosParameters2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErabQosParameters2 of this ErabQosParameters2.  # noqa: E501
        :rtype: ErabQosParameters2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def qci(self) -> int:
        """Gets the qci of this ErabQosParameters2.

        QoS Class Identifier as defined in ETSI TS 123 401 [i.4].  # noqa: E501

        :return: The qci of this ErabQosParameters2.
        :rtype: int
        """
        return self._qci

    @qci.setter
    def qci(self, qci: int):
        """Sets the qci of this ErabQosParameters2.

        QoS Class Identifier as defined in ETSI TS 123 401 [i.4].  # noqa: E501

        :param qci: The qci of this ErabQosParameters2.
        :type qci: int
        """
        if qci is None:
            raise ValueError("Invalid value for `qci`, must not be `None`")  # noqa: E501

        self._qci = qci

    @property
    def qos_information(self) -> QosInformation2:
        """Gets the qos_information of this ErabQosParameters2.


        :return: The qos_information of this ErabQosParameters2.
        :rtype: QosInformation2
        """
        return self._qos_information

    @qos_information.setter
    def qos_information(self, qos_information: QosInformation2):
        """Sets the qos_information of this ErabQosParameters2.


        :param qos_information: The qos_information of this ErabQosParameters2.
        :type qos_information: QosInformation2
        """

        self._qos_information = qos_information
