# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.link_type import LinkType  # noqa: F401,E501
from swagger_server import util


class Links2(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, subscription: LinkType=None):  # noqa: E501
        """Links2 - a model defined in Swagger

        :param subscription: The subscription of this Links2.  # noqa: E501
        :type subscription: LinkType
        """
        self.swagger_types = {
            'subscription': LinkType
        }

        self.attribute_map = {
            'subscription': 'subscription'
        }
        self._subscription = subscription

    @classmethod
    def from_dict(cls, dikt) -> 'Links2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Links2 of this Links2.  # noqa: E501
        :rtype: Links2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subscription(self) -> LinkType:
        """Gets the subscription of this Links2.


        :return: The subscription of this Links2.
        :rtype: LinkType
        """
        return self._subscription

    @subscription.setter
    def subscription(self, subscription: LinkType):
        """Sets the subscription of this Links2.


        :param subscription: The subscription of this Links2.
        :type subscription: LinkType
        """
        if subscription is None:
            raise ValueError("Invalid value for `subscription`, must not be `None`")  # noqa: E501

        self._subscription = subscription
