# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.link_type import LinkType  # noqa: F401,E501
from swagger_server.models.subscription import Subscription  # noqa: F401,E501
from swagger_server import util


class Links10(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _self: LinkType=None, subscription: List[Subscription]=None):  # noqa: E501
        """Links10 - a model defined in Swagger

        :param _self: The _self of this Links10.  # noqa: E501
        :type _self: LinkType
        :param subscription: The subscription of this Links10.  # noqa: E501
        :type subscription: List[Subscription]
        """
        self.swagger_types = {
            '_self': LinkType,
            'subscription': List[Subscription]
        }

        self.attribute_map = {
            '_self': 'self',
            'subscription': 'subscription'
        }
        self.__self = _self
        self._subscription = subscription

    @classmethod
    def from_dict(cls, dikt) -> 'Links10':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Links10 of this Links10.  # noqa: E501
        :rtype: Links10
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _self(self) -> LinkType:
        """Gets the _self of this Links10.


        :return: The _self of this Links10.
        :rtype: LinkType
        """
        return self.__self

    @_self.setter
    def _self(self, _self: LinkType):
        """Sets the _self of this Links10.


        :param _self: The _self of this Links10.
        :type _self: LinkType
        """
        if _self is None:
            raise ValueError("Invalid value for `_self`, must not be `None`")  # noqa: E501

        self.__self = _self

    @property
    def subscription(self) -> List[Subscription]:
        """Gets the subscription of this Links10.

        A link to a subscription.  # noqa: E501

        :return: The subscription of this Links10.
        :rtype: List[Subscription]
        """
        return self._subscription

    @subscription.setter
    def subscription(self, subscription: List[Subscription]):
        """Sets the subscription of this Links10.

        A link to a subscription.  # noqa: E501

        :param subscription: The subscription of this Links10.
        :type subscription: List[Subscription]
        """

        self._subscription = subscription
