# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LinkType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, href: str=None):  # noqa: E501
        """LinkType - a model defined in Swagger

        :param href: The href of this LinkType.  # noqa: E501
        :type href: str
        """
        self.swagger_types = {
            'href': str
        }

        self.attribute_map = {
            'href': 'href'
        }
        self._href = href

    @classmethod
    def from_dict(cls, dikt) -> 'LinkType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LinkType of this LinkType.  # noqa: E501
        :rtype: LinkType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def href(self) -> str:
        """Gets the href of this LinkType.

        URI referring to a resource  # noqa: E501

        :return: The href of this LinkType.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this LinkType.

        URI referring to a resource  # noqa: E501

        :param href: The href of this LinkType.
        :type href: str
        """
        if href is None:
            raise ValueError("Invalid value for `href`, must not be `None`")  # noqa: E501

        self._href = href
