# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.plmn import Plmn  # noqa: F401,E501
from swagger_server import util


class NrBNCellInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nr_bn_cell_gid: str=None, nr_bn_cell_plmn: List[Plmn]=None):  # noqa: E501
        """NrBNCellInfo - a model defined in Swagger

        :param nr_bn_cell_gid: The nr_bn_cell_gid of this NrBNCellInfo.  # noqa: E501
        :type nr_bn_cell_gid: str
        :param nr_bn_cell_plmn: The nr_bn_cell_plmn of this NrBNCellInfo.  # noqa: E501
        :type nr_bn_cell_plmn: List[Plmn]
        """
        self.swagger_types = {
            'nr_bn_cell_gid': str,
            'nr_bn_cell_plmn': List[Plmn]
        }

        self.attribute_map = {
            'nr_bn_cell_gid': 'nrBNCellGId',
            'nr_bn_cell_plmn': 'nrBNCellPlmn'
        }
        self._nr_bn_cell_gid = nr_bn_cell_gid
        self._nr_bn_cell_plmn = nr_bn_cell_plmn

    @classmethod
    def from_dict(cls, dikt) -> 'NrBNCellInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NrBNCellInfo of this NrBNCellInfo.  # noqa: E501
        :rtype: NrBNCellInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nr_bn_cell_gid(self) -> str:
        """Gets the nr_bn_cell_gid of this NrBNCellInfo.

        String representing the NR Cell Identity. Encoded as a bit string (size (36)) as defined in ETSI TS 138 423 [i.17].  # noqa: E501

        :return: The nr_bn_cell_gid of this NrBNCellInfo.
        :rtype: str
        """
        return self._nr_bn_cell_gid

    @nr_bn_cell_gid.setter
    def nr_bn_cell_gid(self, nr_bn_cell_gid: str):
        """Sets the nr_bn_cell_gid of this NrBNCellInfo.

        String representing the NR Cell Identity. Encoded as a bit string (size (36)) as defined in ETSI TS 138 423 [i.17].  # noqa: E501

        :param nr_bn_cell_gid: The nr_bn_cell_gid of this NrBNCellInfo.
        :type nr_bn_cell_gid: str
        """
        if nr_bn_cell_gid is None:
            raise ValueError("Invalid value for `nr_bn_cell_gid`, must not be `None`")  # noqa: E501

        self._nr_bn_cell_gid = nr_bn_cell_gid

    @property
    def nr_bn_cell_plmn(self) -> List[Plmn]:
        """Gets the nr_bn_cell_plmn of this NrBNCellInfo.

        Public land mobile network identities  # noqa: E501

        :return: The nr_bn_cell_plmn of this NrBNCellInfo.
        :rtype: List[Plmn]
        """
        return self._nr_bn_cell_plmn

    @nr_bn_cell_plmn.setter
    def nr_bn_cell_plmn(self, nr_bn_cell_plmn: List[Plmn]):
        """Sets the nr_bn_cell_plmn of this NrBNCellInfo.

        Public land mobile network identities  # noqa: E501

        :param nr_bn_cell_plmn: The nr_bn_cell_plmn of this NrBNCellInfo.
        :type nr_bn_cell_plmn: List[Plmn]
        """
        if nr_bn_cell_plmn is None:
            raise ValueError("Invalid value for `nr_bn_cell_plmn`, must not be `None`")  # noqa: E501

        self._nr_bn_cell_plmn = nr_bn_cell_plmn
