# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.plmn import Plmn  # noqa: F401,E501
from swagger_server import util


class NrNCellInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nr_n_cell_gid: str=None, nr_n_cell_plmn: List[Plmn]=None):  # noqa: E501
        """NrNCellInfo - a model defined in Swagger

        :param nr_n_cell_gid: The nr_n_cell_gid of this NrNCellInfo.  # noqa: E501
        :type nr_n_cell_gid: str
        :param nr_n_cell_plmn: The nr_n_cell_plmn of this NrNCellInfo.  # noqa: E501
        :type nr_n_cell_plmn: List[Plmn]
        """
        self.swagger_types = {
            'nr_n_cell_gid': str,
            'nr_n_cell_plmn': List[Plmn]
        }

        self.attribute_map = {
            'nr_n_cell_gid': 'nrNCellGId',
            'nr_n_cell_plmn': 'nrNCellPlmn'
        }
        self._nr_n_cell_gid = nr_n_cell_gid
        self._nr_n_cell_plmn = nr_n_cell_plmn

    @classmethod
    def from_dict(cls, dikt) -> 'NrNCellInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NrNCellInfo of this NrNCellInfo.  # noqa: E501
        :rtype: NrNCellInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nr_n_cell_gid(self) -> str:
        """Gets the nr_n_cell_gid of this NrNCellInfo.

        String representing the NR Cell Identity. Encoded as a bit string (size (36)) as defined in ETSI TS 138 423 [i.17].  # noqa: E501

        :return: The nr_n_cell_gid of this NrNCellInfo.
        :rtype: str
        """
        return self._nr_n_cell_gid

    @nr_n_cell_gid.setter
    def nr_n_cell_gid(self, nr_n_cell_gid: str):
        """Sets the nr_n_cell_gid of this NrNCellInfo.

        String representing the NR Cell Identity. Encoded as a bit string (size (36)) as defined in ETSI TS 138 423 [i.17].  # noqa: E501

        :param nr_n_cell_gid: The nr_n_cell_gid of this NrNCellInfo.
        :type nr_n_cell_gid: str
        """
        if nr_n_cell_gid is None:
            raise ValueError("Invalid value for `nr_n_cell_gid`, must not be `None`")  # noqa: E501

        self._nr_n_cell_gid = nr_n_cell_gid

    @property
    def nr_n_cell_plmn(self) -> List[Plmn]:
        """Gets the nr_n_cell_plmn of this NrNCellInfo.

        Public land mobile network identities.  # noqa: E501

        :return: The nr_n_cell_plmn of this NrNCellInfo.
        :rtype: List[Plmn]
        """
        return self._nr_n_cell_plmn

    @nr_n_cell_plmn.setter
    def nr_n_cell_plmn(self, nr_n_cell_plmn: List[Plmn]):
        """Sets the nr_n_cell_plmn of this NrNCellInfo.

        Public land mobile network identities.  # noqa: E501

        :param nr_n_cell_plmn: The nr_n_cell_plmn of this NrNCellInfo.
        :type nr_n_cell_plmn: List[Plmn]
        """
        if nr_n_cell_plmn is None:
            raise ValueError("Invalid value for `nr_n_cell_plmn`, must not be `None`")  # noqa: E501

        self._nr_n_cell_plmn = nr_n_cell_plmn
