# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.plmn import Plmn  # noqa: F401,E501
from swagger_server import util


class Nrcgi(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nrcell_id: str=None, plmn: Plmn=None):  # noqa: E501
        """Nrcgi - a model defined in Swagger

        :param nrcell_id: The nrcell_id of this Nrcgi.  # noqa: E501
        :type nrcell_id: str
        :param plmn: The plmn of this Nrcgi.  # noqa: E501
        :type plmn: Plmn
        """
        self.swagger_types = {
            'nrcell_id': str,
            'plmn': Plmn
        }

        self.attribute_map = {
            'nrcell_id': 'nrcellId',
            'plmn': 'plmn'
        }
        self._nrcell_id = nrcell_id
        self._plmn = plmn

    @classmethod
    def from_dict(cls, dikt) -> 'Nrcgi':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Nrcgi of this Nrcgi.  # noqa: E501
        :rtype: Nrcgi
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nrcell_id(self) -> str:
        """Gets the nrcell_id of this Nrcgi.

        String representing the NR Cell Identity. Encoded as a bit string (size (36)) as defined in ETSI TS 138 423 [i.17].  # noqa: E501

        :return: The nrcell_id of this Nrcgi.
        :rtype: str
        """
        return self._nrcell_id

    @nrcell_id.setter
    def nrcell_id(self, nrcell_id: str):
        """Sets the nrcell_id of this Nrcgi.

        String representing the NR Cell Identity. Encoded as a bit string (size (36)) as defined in ETSI TS 138 423 [i.17].  # noqa: E501

        :param nrcell_id: The nrcell_id of this Nrcgi.
        :type nrcell_id: str
        """

        self._nrcell_id = nrcell_id

    @property
    def plmn(self) -> Plmn:
        """Gets the plmn of this Nrcgi.


        :return: The plmn of this Nrcgi.
        :rtype: Plmn
        """
        return self._plmn

    @plmn.setter
    def plmn(self, plmn: Plmn):
        """Sets the plmn of this Nrcgi.


        :param plmn: The plmn of this Nrcgi.
        :type plmn: Plmn
        """
        if plmn is None:
            raise ValueError("Invalid value for `plmn`, must not be `None`")  # noqa: E501

        self._plmn = plmn
