# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from v2.models.base_model_ import Model
from v2.models.enb_info import EnbInfo  # noqa: F401,E501
from v2.models.s_gw_info import SGwInfo  # noqa: F401,E501
from v2 import util


class S1BearerInfoDetailed(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, enb_info: EnbInfo, erab_id: int, s_gw_info: SGwInfo):  # noqa: E501
        """S1BearerInfoDetailed - a model defined in Swagger

        :param enb_info: The enb_info of this S1BearerInfoDetailed.  # noqa: E501
        :type enb_info: EnbInfo
        :param erab_id: The erab_id of this S1BearerInfoDetailed.  # noqa: E501
        :type erab_id: int
        :param s_gw_info: The s_gw_info of this S1BearerInfoDetailed.  # noqa: E501
        :type s_gw_info: SGwInfo
        """

        self._enb_info = enb_info
        self._erab_id = erab_id
        self._s_gw_info = s_gw_info

    # Esta função pega um self e tranforma em dicionário
    # Pega o objeto e retorna ele em formato json
    def json(self):
        return {
            'enb_info': self.enb_info,
            'erab_id': self.erab_id,
            's_gw_info': self.s_gw_info
        }

    @classmethod
    def from_dict(cls, dikt) -> 'S1BearerInfoDetailed':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The S1BearerInfoDetailed of this S1BearerInfoDetailed.  # noqa: E501
        :rtype: S1BearerInfoDetailed
        """
        return util.deserialize_model(dikt, cls)

    @property
    def enb_info(self) -> EnbInfo:
        """Gets the enb_info of this S1BearerInfoDetailed.


        :return: The enb_info of this S1BearerInfoDetailed.
        :rtype: EnbInfo
        """
        return self._enb_info

    @enb_info.setter
    def enb_info(self, enb_info: EnbInfo):
        """Sets the enb_info of this S1BearerInfoDetailed.


        :param enb_info: The enb_info of this S1BearerInfoDetailed.
        :type enb_info: EnbInfo
        """
        # Chamo o construtor da classe EnbInfo passando os parametros ip_address e tunnel_id
        new_enb_info = EnbInfo(**enb_info)
        
        # Chamo o método json da classe EnbInfo para transformar os dados em json
        new_enb_info = new_enb_info.json()
        
        # Finalmente retorno o Json
        self._enb_info = new_enb_info

    @property
    def erab_id(self) -> int:
        """Gets the erab_id of this S1BearerInfoDetailed.

        The attribute that uniquely identifies a S1 bearer for a specific UE, as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :return: The erab_id of this S1BearerInfoDetailed.
        :rtype: int
        """
        return self._erab_id

    @erab_id.setter
    def erab_id(self, erab_id: int):
        """Sets the erab_id of this S1BearerInfoDetailed.

        The attribute that uniquely identifies a S1 bearer for a specific UE, as defined in ETSI TS 136 413 [i.3].  # noqa: E501

        :param erab_id: The erab_id of this S1BearerInfoDetailed.
        :type erab_id: int
        """

        self._erab_id = erab_id

    @property
    def s_gw_info(self) -> SGwInfo:
        """Gets the s_gw_info of this S1BearerInfoDetailed.


        :return: The s_gw_info of this S1BearerInfoDetailed.
        :rtype: SGwInfo
        """
        return self._s_gw_info

    @s_gw_info.setter
    def s_gw_info(self, s_gw_info: SGwInfo):
        """Sets the s_gw_info of this S1BearerInfoDetailed.


        :param s_gw_info: The s_gw_info of this S1BearerInfoDetailed.
        :type s_gw_info: SGwInfo
        """
        # Chamo o construtor da classe SGwInfo passando os parametros ip_address e tunnel_id
        new_s_gw_info = SGwInfo(**new_s_gw_info)
        
        # Chamo o método json da classe SGwInfo para transformar os dados em json
        new_s_gw_info = new_s_gw_info.json()
        
        # Finalmente retorno o Json
        self._s_gw_info = new_s_gw_info
