# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TriggerNr(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    _0 = "0"
    _1 = "1"
    _2 = "2"
    _10 = "10"
    _11 = "11"
    _12 = "12"
    _13 = "13"
    _14 = "14"
    _15 = "15"
    _20 = "20"
    _21 = "21"
    _30 = "30"
    _31 = "31"
    def __init__(self):  # noqa: E501
        """TriggerNr - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TriggerNr':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TriggerNr of this TriggerNr.  # noqa: E501
        :rtype: TriggerNr
        """
        return util.deserialize_model(dikt, cls)
