# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from v2.models.base_model_ import Model
from v2 import util


class Type(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    _0 = "0"
    _1 = "1"
    _2 = "2"
    _3 = "3"
    _4 = "4"
    def __init__(self):  # noqa: E501
        """Type - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }
    
        # Esta função pega um self e tranforma em dicionário
    # Pega o objeto e retorna ele em formato json
    def json(self):
        return {

        }



    @classmethod
    def from_dict(cls, dikt) -> 'Type':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Type of this Type.  # noqa: E501
        :rtype: Type
        """
        return util.deserialize_model(dikt, cls)
