# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from v2.models.base_model_ import Model
from v2 import util


class InlineSubscription(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, subscription_type: str=None):  # noqa: E501
        """InlineSubscription - a model defined in Swagger

        :param subscription_type: The subscription_type of this InlineSubscription.  # noqa: E501
        :type subscription_type: str
        """
        self.swagger_types = {
            'subscription_type': str
        }

        self.attribute_map = {
            'subscription_type': 'subscriptionType'
        }
        self._subscription_type = subscription_type

    @classmethod
    def from_dict(cls, dikt) -> 'InlineSubscription':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InlineSubscription of this InlineSubscription.  # noqa: E501
        :rtype: InlineSubscription
        """
        return util.deserialize_model(dikt, cls)

    @property
    def subscription_type(self) -> str:
        """Gets the subscription_type of this InlineSubscription.


        :return: The subscription_type of this InlineSubscription.
        :rtype: str
        """
        return self._subscription_type

    @subscription_type.setter
    def subscription_type(self, subscription_type: str):
        """Sets the subscription_type of this InlineSubscription.


        :param subscription_type: The subscription_type of this InlineSubscription.
        :type subscription_type: str
        """
        if subscription_type is None:
            raise ValueError("Invalid value for `subscription_type`, must not be `None`")  # noqa: E501

        self._subscription_type = subscription_type
