# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.links10 import Links10  # noqa: F401,E501
from swagger_server import util


class SubscriptionLinkList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, links: Links10=None):  # noqa: E501
        """SubscriptionLinkList - a model defined in Swagger

        :param links: The links of this SubscriptionLinkList.  # noqa: E501
        :type links: Links10
        """
        self.swagger_types = {
            'links': Links10
        }

        self.attribute_map = {
            'links': '_links'
        }
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'SubscriptionLinkList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SubscriptionLinkList of this SubscriptionLinkList.  # noqa: E501
        :rtype: SubscriptionLinkList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def links(self) -> Links10:
        """Gets the links of this SubscriptionLinkList.


        :return: The links of this SubscriptionLinkList.
        :rtype: Links10
        """
        return self._links

    @links.setter
    def links(self, links: Links10):
        """Sets the links of this SubscriptionLinkList.


        :param links: The links of this SubscriptionLinkList.
        :type links: Links10
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links
